# Generated by Django 2.1.7 on 2019-03-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=35)),
                ('e_description', models.TextField(max_length=255)),
                ('e_category', models.CharField(choices=[('Con', 'Conference'), ('Sem', 'Seminar'), ('Pres', 'Presentation')], max_length=4)),
                ('e_start_date', models.DateField()),
                ('e_end_date', models.DateField()),
                ('e_start_time', models.DateTimeField()),
                ('e_end_time', models.DateTimeField()),
                ('e_location', models.CharField(max_length=50)),
                ('registrants', models.BooleanField()),
                ('e_image', models.ImageField(height_field=60, upload_to='', width_field=60)),
                ('e_adult_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('e_child_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(blank=True, choices=[('A', 'Admin'), ('U', 'User')], max_length=1)),
            ],
        ),
    ]
