# Generated by Django 2.1.7 on 2019-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='e_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('U', 'User'), ('A', 'Admin')], max_length=5),
        ),
    ]
