# Generated by Django 2.1.7 on 2019-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190401_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='e_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
